# Generated by Django 5.2.4 on 2025-07-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_delete_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featcherd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
